# Generated by Django 5.2.3 on 2025-06-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Envio')),
                ('status', models.CharField(choices=[('aguardando_envio', 'Aguardando Envio'), ('em_preparo_cozinha', 'Em Preparo'), ('pronto_para_entrega', 'Pronto para Entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando_envio', max_length=30, verbose_name='Status do Envio')),
                ('observacoes_envio', models.TextField(blank=True, null=True, verbose_name='Observações para Cozinha')),
            ],
            options={
                'verbose_name': 'Envio para Cozinha',
                'verbose_name_plural': 'Envios para Cozinha',
                'ordering': ['-data_hora_envio'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Pedido')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_preparo', 'Em Preparo'), ('pronto_para_entrega', 'Pronto para Entrega'), ('entregue', 'Entregue'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=30, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Pedido')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesa.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_hora_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cardapio.itemcardapio', verbose_name='Item do Cardápio')),
                ('envio_cozinha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_enviados', to='pedido.enviocozinha', verbose_name='Envio para Cozinha')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pedido.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.AddField(
            model_name='enviocozinha',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cozinha', to='pedido.pedido', verbose_name='Pedido Principal'),
        ),
    ]
