# Generated by Django 5.2.3 on 2025-06-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
        ('mesa', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cardapio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.itemcardapio', verbose_name='Item do Cardápio'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='mesa.mesa', verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_preparo', 'Em Preparo'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status do Pedido'),
        ),
    ]
