# Generated by Django 5.2.3 on 2025-06-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_remove_pedido_observacoes_pedido_valor_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='gorjeta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor da Gorjeta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes_finalizacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Cliente na Finalização'),
        ),
    ]
