# Generated by Django 5.2.3 on 2025-06-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_gorjeta_pedido_observacoes_finalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='couvert_artistico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Couvert Artístico'),
        ),
    ]
