# Generated by Django 5.2.3 on 2025-06-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_couvert_artistico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='couvert_artistico',
        ),
    ]
