# Generated by Django 5.2.4 on 2025-07-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_cardapio', to='configuracao.estabelecimento', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Categoria de Cardápio',
                'verbose_name_plural': 'Categorias de Cardápio',
                'ordering': ['nome'],
                'unique_together': {('estabelecimento', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cardapio_imagens/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cardapio.categoria')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_cardapio', to='configuracao.estabelecimento', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Item de Cardápio',
                'verbose_name_plural': 'Itens de Cardápio',
                'ordering': ['categoria__nome', 'nome'],
                'unique_together': {('estabelecimento', 'nome')},
            },
        ),
    ]
