# Generated by Django 5.2.3 on 2025-06-30 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadaGarcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chamada', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Chamada')),
                ('atendida', models.BooleanField(default=False, verbose_name='Atendida')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas_garcom', to='mesa.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Chamada de Garçom',
                'verbose_name_plural': 'Chamadas de Garçom',
                'ordering': ['data_hora_chamada'],
            },
        ),
    ]
