# Generated by Django 5.2.4 on 2025-07-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0001_initial'),
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadaGarcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chamada', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvida', 'Resolvida')], default='pendente', max_length=10)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas_garcom', to='configuracao.estabelecimento', verbose_name='Estabelecimento')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='mesa.mesa')),
            ],
            options={
                'verbose_name': 'Chamada de Garçom',
                'verbose_name_plural': 'Chamadas de Garçons',
                'ordering': ['status', '-data_hora_chamada'],
            },
        ),
    ]
