# Generated by Django 5.2.4 on 2025-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamadagarcom',
            options={'ordering': ['status', '-data_hora_chamada'], 'verbose_name': 'Chamada de Garçom', 'verbose_name_plural': 'Chamadas de Garçom'},
        ),
        migrations.RemoveField(
            model_name='chamadagarcom',
            name='atendida',
        ),
        migrations.AddField(
            model_name='chamadagarcom',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('resolvida', 'Resolvida')], default='pendente', max_length=20, verbose_name='Status da Chamada'),
        ),
    ]
