# Generated by Django 5.2.4 on 2025-07-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Número ou identificador da mesa (ex: 'Mesa 5', 'Balcão A')", max_length=50)),
                ('capacidade', models.IntegerField(default=2, help_text='Capacidade máxima de pessoas nesta mesa')),
                ('status', models.CharField(choices=[('LIVRE', 'Livre'), ('OCUPADA', 'Ocupada'), ('RESERVADA', 'Reservada'), ('MANUTENCAO', 'Em Manutenção')], default='LIVRE', max_length=15, verbose_name='Status da Mesa')),
                ('descricao', models.TextField(blank=True, help_text='Breve descrição ou localização da mesa (opcional)', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='configuracao.estabelecimento', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
                'unique_together': {('numero', 'estabelecimento')},
            },
        ),
    ]
