# Generated by Django 5.2.4 on 2025-07-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número da Mesa')),
                ('capacidade', models.IntegerField(default=4, verbose_name='Capacidade de Pessoas')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Mesa Disponível')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='configuracao.estabelecimento', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
                'unique_together': {('estabelecimento', 'numero')},
            },
        ),
    ]
