# Generated by Django 5.2.4 on 2025-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Estabelecimento')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato Principal')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email de Contato')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX')),
                ('logotipo_cabecalho', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo do Cabeçalho')),
                ('imagem_fundo_sistema', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo do Sistema')),
                ('cor_primaria', models.CharField(default='#1976D2', max_length=7, verbose_name='Cor Primária (Hex)')),
                ('cor_secundaria', models.CharField(default='#FFC107', max_length=7, verbose_name='Cor Secundária (Hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'ordering': ['nome'],
            },
        ),
    ]
