# Generated by Django 4.2.23 on 2025-07-14 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ativacao', models.DateField(verbose_name='Data de Ativação')),
                ('data_desativacao', models.DateField(blank=True, null=True, verbose_name='Data de Desativação')),
                ('estado', models.CharField(choices=[('ATIVA', 'Ativa'), ('TESTE', 'Em Período de Teste'), ('CANCELADA', 'Cancelada'), ('SUSPENSA', 'Suspensa'), ('FINALIZADA', 'Finalizada')], default='TESTE', max_length=20, verbose_name='Estado da Assinatura')),
                ('valor_ativacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Ativação/Configuração Inicial')),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal da Assinatura')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('CARTAO', 'Cartão de Crédito/Débito'), ('BOLETO', 'Boleto Bancário'), ('PIX', 'Pix'), ('TRANSFERENCIA', 'Transferência Bancária'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_assinaturas', to='configuracao.estabelecimento', verbose_name='Estabelecimento')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Assinatura do Estabelecimento',
                'verbose_name_plural': 'Assinaturas dos Estabelecimentos',
            },
        ),
    ]
