# Generated by Django 4.2.23 on 2025-07-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0002_assinaturaestabelecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('celular', models.CharField(help_text='Número de celular do cliente (chave única)', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Celular')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('foto_cliente', models.ImageField(blank=True, null=True, upload_to='clientes/fotos/', verbose_name='Foto do Cliente')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='configuracao.estabelecimento', verbose_name='Estabelecimento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_completo'],
            },
        ),
    ]
